language: bash
services: docker

env:
  - DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=5.6-fpm
  - DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=7.0-fpm
  - DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=7.1-fpm
  - DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=7.2-rc-fpm
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=5.6-fpm
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.0-fpm
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.1-fpm
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.2-rc-fpm

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-ce

install:
  - git clone https://github.com/yiisoft/yii2.git ~/build/yiisoft/yii2-docker/tests/yii2

before_script:
  - pwd
  - docker version
  - docker info
  - docker-compose version
  - cp .env-dist .env

script:
  - docker-compose build
  - docker-compose run --rm php php /tests/requirements.php

after_script:
  - docker images

# vim:set et ts=2 sw=2:
