language: bash
services: docker

env:
  - DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=5.6-fpm-alpine
  - DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=7.0-fpm-alpine
  - DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=7.1-fpm-alpine
  - DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=7.2-rc-fpm-alpine
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=5.6-fpm
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.0-fpm
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.1-fpm
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.2-rc-fpm
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=5.6-apache
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.0-apache
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.1-apache
  - DOCKERFILE_FLAVOUR=debian PHP_BASE_IMAGE_VERSION=7.2-rc-apache

matrix:
  allow_failures:
    # Alpine 5.6-7.1 has a broken ImageMagick installation
    - env: DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=5.6-fpm-alpine
    - env: DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=7.0-fpm-alpine
    - env: DOCKERFILE_FLAVOUR=alpine PHP_BASE_IMAGE_VERSION=7.1-fpm-alpine

before_install:
  - export TEST_YII_VERSION=2.0.13
  - export DOCKER_COMPOSE_VERSION=1.16.1
  - sudo apt-get update
  - sudo apt-get install docker-ce
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - git clone https://github.com/yiisoft/yii2.git ~/build/yiisoft/yii2-docker/tests/yii2

before_script:
  - pwd
  - docker version
  - docker info
  - docker-compose version
  - cp .env-dist .env

script:
  - docker-compose build
  - docker-compose run --rm php php /tests/requirements.php

after_script:
  - docker images

# vim:set et ts=2 sw=2:
